
services:
  ocr:
    build:
      context: ./
      dockerfile: sparrow-data/ocr/Dockerfile
    container_name: ocr-container
    working_dir: /ocr
    volumes:
      - ./sparrow-data/ocr/:/ocr
    ports:
      - "8001:80011"
    runtime: nvidia  # Использование GPU runtime
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Указываем все доступные GPU
